version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wintercms-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=wintercms
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: wintercms-db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wintercms
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
